// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATTa0ihVMqay-VRYzUqoCG_2Denyy1h4g',
    appId: '1:733835057972:android:6bc629b0524deaccb9e361',
    messagingSenderId: '733835057972',
    projectId: 'flutter-firebase-push-no-f641e',
    storageBucket: 'flutter-firebase-push-no-f641e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI0kfGAv62KouJel6Pb2Hhb6hq8-BgbYQ',
    appId: '1:733835057972:ios:3cca4613c415354eb9e361',
    messagingSenderId: '733835057972',
    projectId: 'flutter-firebase-push-no-f641e',
    storageBucket: 'flutter-firebase-push-no-f641e.firebasestorage.app',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI0kfGAv62KouJel6Pb2Hhb6hq8-BgbYQ',
    appId: '1:733835057972:ios:3cca4613c415354eb9e361',
    messagingSenderId: '733835057972',
    projectId: 'flutter-firebase-push-no-f641e',
    storageBucket: 'flutter-firebase-push-no-f641e.firebasestorage.app',
    iosBundleId: 'com.example.firebasePushNotification',
  );
}
